export const data = [
  {
    id: 1,
    name: "Maybelline",
    img: "./images/eyeshadow1.jpg",
    category: "Eye Shadow",
  },
  {
    id: 2,
    name: "Elf Sculpting Silk Eyeshadow",
    img: "./images/eyeshadow2.jpg",
    category: "Eye Shadow",
  },
  {
    id: 3,
    name: "Elf Clay Eyeshadow Palette",
    img: "./images/eyeshadow3.jpg",
    category: "Eye Shadow",
  },
  {
    id: 4,
    name: "Mabeline super stay under eye concealer",
    img: "./images/concealer1.jpg",
    category: "Concealer",
  },
  {
    id: 5,
    name: "Ardell Natural",
    img: "./images/eyelashes1.jpg",
    category: "Eye Lashes",
  },
  {
    id: 6,
    name: "Ardell Professional",
    img: "./images/eyelashes2.jpg",
    category: "Eye Lashes",
  },
  {
    id: 7,
    name: "Milani prime shield face primer (big)",
    img: "./images/primer1.jpg",
    category: "Primer",
  },
  {
    id: 8,
    name: "NYX Primer",
    img: "./images/primer1.jpg",
    category: "Primer",
  },
  {
    id: 9,
    name: "Rimmel lasting finish breathable finishing powder",
    img: "./images/powder1.jpg",
    category: "Powder",
  },
  {
    id: 10,
    name: "Elf shimmer highlighting powder starlight glow",
    img: "./images/powder2.jpg",
    category: "Powder",
  },
  {
    id: 11,
    name: "Elf illuminating palette",
    img: "./images/palette1.jpg",
    category: "Pallete",
  },
  {
    id: 12,
    name: "Glitter nail polish",
    img: "./images/nailpolish1.jpg",
    category: "Nail Polish",
  },
  {
    id: 14,
    name: "Maybelline Snapscara",
    img: "./images/mascara1.jpg",
    category: "Mascara",
  },
  {
    id: 15,
    name: "Elf moisturizing lipstick (red carpet)",
    img: "./images/lipstick1.jpg",
    category: "Lipstick",
  },
  {
    id: 16,
    name: "Elf moisturizing lipstick (wine tour)",
    img: "./images/lipstick2.jpg",
    category: "Lipstick",
  },
  {
    id: 18,
    name: "Mabeline dream radiant liquid foundation",
    img: "./images/foundation1.jpg",
    category: "Foundation",
  },
  {
    id: 19,
    name: "Infallible Pro-Last",
    img: "./images/pencil1.jpg",
    category: "Pencil",
  },
  {
    id: 20,
    name: "Photo Chic Eyeliner Pencil",
    img: "./images/pencil2.jpg",
    category: "Pencil",
  },
];
